
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
#      消息发送到交换机确认机制,是否确认回调
    publisher-returns: true

  devtools:
      restart:
        enabled: false
server:
  port: 8088