server:
  port: 8861
dubbo:
  application:
    name: dubbo-provider
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880
spring:
  main:
    allow-bean-definition-overriding: true
